### ISSUE TITLE
"cargo install kdash" fails during compilation

### ISSUE THREAD

**Issue by wintermi** [kdash-rs/kdash#104]
**Describe the bug**
Executing `cargo install kdash` to install the v0.2.3 crate fails during compilation

**To Reproduce**
1. Execute `cargo install kdash`

**Expected behavior**
Installation of the crate

**Screenshots**
The following is output during the install:

```
error: failed to run custom build command for `k8s-openapi v0.13.0`

Caused by:
  process didn't exit successfully: `/tmp/cargo-installJLFrYi/release/build/k8s-openapi-405af67896caa110/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at '
  None of the v1_* features are enabled on the k8s-openapi crate.

  The k8s-openapi crate requires a feature to be enabled to indicate which version of Kubernetes it should support.

  If you're using k8s-openapi in a binary crate, enable the feature corresponding to the minimum version of API server that you want to support. It may be possible that your binary crate does not directly depend on k8s-openapi. In this case, add a dependency on k8s-openapi, then enable the corresponding feature.

  If you're using k8s-openapi in a library crate, add a dev-dependency on k8s-openapi and enable one of the features there. This way the feature will be enabled when buildings tests and examples of your library, but not when building the library itself. It may be possible that your library crate does not directly depend on k8s-openapi. In this case, add a dev-dependency on k8s-openapi, then enable the corresponding feature.

  Library crates *must not* enable any features in their direct dependency on k8s-openapi, only in their dev-dependency. The choice of Kubernetes version to support should be left to the final binary crate, so only the binary crate should enable a specific feature. If library crates also enable features, it can cause multiple features to be enabled simultaneously, which k8s-openapi does not support.

  If you want to restrict your library crate to support only a single specific version or range of versions of Kubernetes, please use the k8s_* version-specific macros to emit different code based on which feature gets enabled in the end.', /home/matt/.cargo/registry/src/github.com-1ecc6299db9ec823/k8s-openapi-0.13.0/build.rs:9:42
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: failed to compile `kdash v0.2.3`, intermediate artifacts can be found at `/tmp/cargo-installJLFrYi`
```

**Desktop (please complete the following information):**
 - OS and OS version: Ubuntu 20.04
 - Terminal name and version: Kitty
 - Shell name and version: bash
 - KDash version: v0.2.3

**Additional context**
Cargo looks to be retrieving a new version of the `k8s-openapi` crate than what kdash states via the `Cargo.toml` file.  Which looks to be due to other dependencies requiring the newer version of the crate.

**Comment by deepu105** [comment]
Thanks for the report. Need to check what changed

**Comment by deepu105** [comment]
This is quite strange, when I run `cargo run` there is no issue but `cargo install` fails. I'm trying to figure out where the dependency comes from

**Comment by deepu105** [comment]
I coulnd't find the issue, but atleast I updated the dependencies to latest and hence with next release this should be fixed. In the mean time could you use homebrew or the binary

**Comment by deepu105** [comment]
fixed via https://github.com/kdash-rs/kdash/commit/47c9fc55ecaaafd6bee3d26bb8bb335414fe1acf

**Comment by deepu105** [comment]
I made a new release 0.2.4, can you please try that? it should be available in few minutes

**Comment by wintermi** [comment]
I have tested upgrading from v0.2.3 as well as a clean install and everything is now compiling correctly.  Thanks for the update.

**Comment by deepu105** [comment]
Thank you

Thanks & Regards,
Deepu
