### ISSUE TITLE
Dark theme: the blue font color is barely visible

### ISSUE THREAD

**Issue by sed-i** [kdash-rs/kdash#162]
**Is your feature request related to a problem? Please describe.**
The color chosen for "KDash - A simple Kubernetes dashboard" and others is barely visible on a black screen.

**Describe the solution you'd like**
Use white or something else that has good contrast.

(awesome tool, btw)

**Comment by deepu105** [comment]
Can you provide a screenshot please?

**Comment by sed-i** [comment]
Here it is:
![Screenshot from 2022-01-27 10-16-23](https://user-images.githubusercontent.com/82407168/151388845-879e5c47-938e-40e7-9fb8-001e669b8a79.jpg)

**Comment by deepu105** [comment]
Which OS and terminal are you on? 

Anyway, the good news is @omid fixed the color contrast recently in #157 and I'll probably do some more work to avoid slight changes in color by using RGB instead of color labels and long terms I would like to make colors configurable

**Comment by deepu105** [comment]
fixed via https://github.com/kdash-rs/kdash/commit/39f727a396eb0bb46e3202701eb9aae98bfb3465

**Comment by deepu105** [comment]
@sed-i please check the new release 0.3.0 and let me know if you still see any issues. I have changed to use fixed RGB values for all colors with a contrast ratio of 7:1 or higher confirming to `WCAG AAA:` accessibility ratings

**Comment by sed-i** [comment]
Amazing! Thanks so much.
