### ISSUE TITLE
The dashboard  stuck inexplicably

### ISSUE THREAD

**Issue by hantmac** [kdash-rs/kdash#18]
After running for a while, the dashboard  stuck inexplicably.

**Comment by deepu105** [comment]
Is there any specific error that you see? Honestly its kind of impossible
for me to guess what the issue is with this information

**Comment by deepu105** [comment]
or can you make a screen recording of the error and share that please?

Also details like your OS, Kubectl version etc

**Comment by hantmac** [comment]
There is no error reported and the os is `darwin`, 

kubectl version:

```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.1", GitCommit:"c4d752765b3bbac2237bf87cf0b1c2e307844666", GitTreeState:"clean", BuildDate:"2020-12-19T08:38:20Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.9-aliyun.1", GitCommit:"4f7ea78", GitTreeState:"", BuildDate:"2020-05-08T07:29:59Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```
I will make a screen  recording , wait

**Comment by deepu105** [comment]
thank you appreciate that

**Comment by hantmac** [comment]
![](https://tva1.sinaimg.cn/large/008i3skNgy1gqeu10af59g31c60u01kx.gif)


I made a screen cast and after I start `kdash` for a while, the screen stuck and can't exit even press any key.

**Comment by deepu105** [comment]
Hi, the screencast you attached shows something else, may be you added the wrong one, can you check

**Comment by hantmac** [comment]
> Hi, the screencast you attached shows something else, may be you added the wrong one, can you check

Sorry, made a mistake, some wrong with my git

**Comment by deepu105** [comment]
Any luck with the screencast?

**Comment by hantmac** [comment]
> Any luck with the screencast?

Sorry for that, I am busying these days.
