### ISSUE TITLE
"cargo install kdash" k8s-openapi error

### ISSUE THREAD

**Issue by valorl** [kdash-rs/kdash#181]
**Describe the bug**
Cannot install/build with `cargo install kdash`. Fails on running `k8s-openapi`.

**To Reproduce**
Steps to reproduce the behavior or a screencast
1. `cargo install kdash`
2. See error

**Expected behavior**
Builds and installs.

**Screenshots**

**Desktop (please complete the following information):**
 - OS and OS version: Windows / WSL / Arch
 - Terminal name and version: st
 - Shell name and version: zsh
 - Kubectl Client Version: `version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b695d79d4f967c403a96986f1750a35eb75e75f1", GitTreeState:"archive", BuildDate:"2021-11-18T21:20:32Z", GoVersion:"go1.17.3", Compiler:"gc", Platform:"linux/amd64"}`
 - Kubectl Server Version: `version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.11-eks-f17b81", GitCommit:"f17b810c9e5a82200d28b6210b458497ddfcf31b", GitTreeState:"clean", BuildDate:"2021-10-15T21:46:21Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}`
 - KDash version: `v0.3.0`
 
**Additional context**:
I've seen #104 and #111. I assume this is a new instance of a similar issue since those were fixed.

**Comment by bladepoint6969** [comment]
I'm also seeing this issue.

- OS and OS version: Pop!_OS 21.10
- Terminal name and version: gnome-terminal 3.38.1
- Shell name and version: bash 5.1.8
- Kubectl Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5", GitCommit:"c285e781331a3785a7f436042c65c5641ce8a9e9", GitTreeState:"clean", BuildDate:"2022-03-16T15:58:47Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"linux/amd64"}
- Kubectl Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-25T21:19:12Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/amd64"}
- KDash version: v0.3.0

**Comment by deepu105** [comment]
do you see any error on console?

**Comment by bladepoint6969** [comment]
I get the following error:
```
error: failed to run custom build command for `k8s-openapi v0.14.0`

Caused by:
  process didn't exit successfully: `/tmp/cargo-install0okXDW/release/build/k8s-openapi-a26aa6c8ea68ba69/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at '
  None of the v1_* features are enabled on the k8s-openapi crate.

  The k8s-openapi crate requires a feature to be enabled to indicate which version of Kubernetes it should support.

  If you're using k8s-openapi in a binary crate, enable the feature corresponding to the minimum version of API server that you want to support. It may be possible that your binary crate does not directly depend on k8s-openapi. In this case, add a dependency on k8s-openapi, then enable the corresponding feature.

  If you're using k8s-openapi in a library crate, add a dev-dependency on k8s-openapi and enable one of the features there. This way the feature will be enabled when buildings tests and examples of your library, but not when building the library itself. It may be possible that your library crate does not directly depend on k8s-openapi. In this case, add a dev-dependency on k8s-openapi, then enable the corresponding feature.

  Library crates *must not* enable any features in their direct dependency on k8s-openapi, only in their dev-dependency. The choice of Kubernetes version to support should be left to the final binary crate, so only the binary crate should enable a specific feature. If library crates also enable features, it can cause multiple features to be enabled simultaneously, which k8s-openapi does not support.

  If you want to restrict your library crate to support only a single specific version or range of versions of Kubernetes, please use the k8s_* version-specific macros to emit different code based on which feature gets enabled in the end.', /home/ben/.cargo/registry/src/github.com-1ecc6299db9ec823/k8s-openapi-0.14.0/build.rs:9:42
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: failed to compile `kdash v0.3.0`, intermediate artifacts can be found at `/tmp/cargo-install0okXDW`

Caused by:
  build failed
```
![Kdash Error](https://user-images.githubusercontent.com/8454993/161908903-350a85e3-2fa3-4416-b3e9-006feb15f9d4.png)

**Comment by bladepoint6969** [comment]
When I run with `RUST_BACKTRACE=1`, I get this trace:
```
stack backtrace:
     0: rust_begin_unwind
               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:498:5
     1: core::panicking::panic_fmt
               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panicking.rs:116:14
     2: core::panicking::panic_display
               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panicking.rs:72:5
     3: core::panicking::panic_str
               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panicking.rs:56:5
     4: core::option::expect_failed
               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/option.rs:1817:5
     5: core::option::Option<T>::expect
     6: build_script_build::main
     7: core::ops::function::FnOnce::call_once
```

**Comment by bladepoint6969** [comment]
Ok, so I did a litte digging once I noticed that the error message gave the version as `v0.14.0`.

Turns out that when running `cargo install` with either the path or crate name, it downloads and tries to compile both version 0.14.0 and 0.13.1. A `cargo build --release` does not do this:
![Screenshot from 2022-04-06 03-00-56](https://user-images.githubusercontent.com/8454993/161915084-3285b15b-1d0c-4fd9-812e-5393037f4c0c.png)

I ran `cargo install --locked kdash` and that installed it successfully, with a warning about `socket2 v0.4.3` being yanked.

We still don't know what's ultimately causing the problem, but at least there's a workaround.

**Comment by deepu105** [comment]
thats really strange. k8s-openapi has been causing a lot of headaches to be honest. Last time this issue happened I updated the dependencies and it was fixed so I guess the issue comes from some transitive dependency depending on another version of k8s-openapi. I can confirm that your workaround does the trick I'm gonna document that, I'll make a patch release to see  if that will fix this

**Comment by deepu105** [comment]
can you try with latest release. it works now, but probably the issue will reappear when some dependencies change
