### ISSUE TITLE
No CPU/Mem metrics

### ISSUE THREAD

**Issue by TheDutchMC** [kdash-rs/kdash#19]
Hey there,

First of all, loving the project so far! Keep up the awesome work.

I'm getting everything from the cluster, pods, etc all works file. But metrics, i.e cpu and memory show 0, which I doubt is correct.
What is required in terms of (special) K8s configuration to get these two metrics working?

Thanks! 

**Edit** I'm on K8s 1.20

**Comment by deepu105** [comment]
Thank you for the kind words.

Metrics are gathered from the metrics server which needs to be deployed on the cluster. K8s clusters on GCP comes with it by default but Kind doesnt for examples. So if you are running your own k8s on bare metal or cloud you should have a metrics server deployed on it. Basically its the same thing that is needed for `kubectl top node`. So run this to see if it gives you an output if so then this could be an issue on KDash side, else its just missing metrics server. See this docs for instructions on how to setup metrics -> https://github.com/kubernetes/metrics/blob/master/IMPLEMENTATIONS.md

**Comment by TheDutchMC** [comment]
Yep that was it! Thanks!
