### ISSUE TITLE
Provide arm binaries

### ISSUE THREAD

**Issue by patrickelectric** [kdash-rs/kdash#198]
**Is your feature request related to a problem? Please describe.**
There is no arm binaries available for release, armv7 and aarch64

**Describe the solution you'd like**
To have arm binaries and not compiled the project manully.

**Describe alternatives you've considered**
Compile it manually.

**Additional context**
There is no other alternative over compiling the project.

**Comment by patrickelectric** [comment]
Thanks @deepu105! I'll definitely test.

**Comment by deepu105** [comment]
Hi @patrickelectric I still haven't had the chance to do this. If you are familiar with the Rust toolchain could you please help with this? Should be fairly straightforward to add the target to https://github.com/kdash-rs/kdash/blob/main/.github/workflows/cd.yml and test if everything is working as expected

**Comment by deepu105** [comment]
Tha latest release v0.3.3 has ARM and aarch64 binaries. @patrickelectric can you please test and let me know if they work as expected? Please note that the `copy to clipboard` feature is disabled on those due to some library compatibility issues
