### ISSUE TITLE
Dual crossterm versions in 0.3.1

### ISSUE THREAD

**Issue by sidju** [kdash-rs/kdash#205]
**Describe the bug**
Dual Crossterm versions. This risks unexpected issues and needlessly bloats binary size.

**To Reproduce**
on a clean compile log shows both Crossterm 0.22.1 and 0.23.2 are compiled.

**Expected behavior**
A singular version chosen to match the one used by Tui is installed.

**Desktop (please complete the following information):**
  Most is irrelevant as this is a minor Cargo.toml issue.
 - KDash version: 0.3.1

**Additional context**
(If I remember correctly the standard solution is to set '*' as version for crates whose version is selected by other crates. Might need to delete cargo.lock also)

**Comment by deepu105** [comment]
Thanks for reporting. I would appreciate if you could do a PR to fix it as I'm bit tight on time now

**Comment by deepu105** [comment]
outdated
