### ISSUE TITLE
kdash fails to start due to tcp connect error on Windows

### ISSUE THREAD

**Issue by Cyneath** [kdash-rs/kdash#21]
**Describe the bug**
I use k3d to bootstrap a k8s cluster locally. When I now open kdash, the error 
`HyperError: error trying to connect: tcp connect error: Die angeforderte Adresse ist in diesem Kontext ungültig. (os error 10049)`
appears after some seconds and I'm not able to see the resource overview. With other tools (kubectl, k9s) I can connect to the cluster without any problems.

Also, sometimes when I press Ctrl-C to close kdash after the previous mentioned error appeared, I get the following error in the cmd:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
OSError: [Errno 22] Invalid argument
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='cp1252'>
OSError: [Errno 22] Invalid argument
```

**To Reproduce**
1. Create a local k8s cluster using `k3d cluster create`
2. Start kdash using the `kdash `command
3. Wait a few seconds

**Expected behavior**
The resource overview loads.

**Screenshots**
![image](https://user-images.githubusercontent.com/53078027/117637049-baee2980-b181-11eb-84f7-66bb4531a1ed.png)

https://user-images.githubusercontent.com/53078027/117637156-d5c09e00-b181-11eb-9e29-f66cbd362169.mp4

**Desktop (please complete the following information):**
 - OS and OS version: Windows 10
 - Terminal name and version: Windows CMD
 - Shell name and version: -
 - Kubectl Client Version: v1.21.0
 - Kubectl Server Version: v1.20.5+k3s1
 - KDash version: 0.0.8

**Additional context**
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:31:21Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.5+k3s1", GitCommit:"355fff3017b06cde44dbd879408a3a6826fa7125", GitTreeState:"clean", BuildDate:"2021-03-31T06:21:52Z", GoVersion:"go1.15.10", Compiler:"gc", Platform:"linux/amd64"}
```

```
k3d version
k3d version v4.4.1
k3s version v1.20.5-k3s1 (default)
```

**Comment by Cyneath** [comment]
> Thank you for reporting this. I haven't tried k3d. I'll try to replicate this. In the mean time what happens if you press escape after the error? does it appear again?

Yes, the error appears again when I press ESC (tested with 0.0.8 and 0.0.9).

> I just tried with k3d (4.4.3) and everything is working as expected, including utilizations. So may be this is happening only in Windows as I tested on Linux. I'll test on my windows box when I find time. In the meantime, could you check with latest KDash release 0.0.9 just to be sure?

With 0.0.9 I now get the following error messages for "resource", "namespace" and "nodes" cyclically:
`Failed to get resource. HyperError(hyper::Error(Connect, ConnectError("tcp connect error", Os { code: 10049, kind: AddrNotAvailable, message: "Die angeforderte Adresse ist in diesem Kontext ungültig." })))`
`Failed to get namespaces. HyperError(hyper::Error(Connect, ConnectError("tcp connect error", Os { code: 10049, kind: AddrNotAvailable, message: "Die angeforderte Adresse ist in diesem Kontext ungültig." })))`
`Failed to get nodes. HyperError(hyper::Error(Connect, ConnectError("tcp connect error", Os { code: 10049, kind: AddrNotAvailable, message: "Die angeforderte Adresse ist in diesem Kontext ungültig." })))`

https://user-images.githubusercontent.com/53078027/117789228-68c40b80-b248-11eb-9ecf-1a86f8a14466.mp4

I also tested with k3d 4.4.3: no difference.

**Comment by deepu105** [comment]
I was able to reproduce this on Windows. Also seems like there are more issues on Windows. Gonna be quite annoying to track down 🤦

**Comment by deepu105** [comment]
So it seems like an issue in the Rust Kubernetes lib, I have opened an issue to track it there https://github.com/clux/kube-rs/issues/518

**Comment by deepu105** [comment]
A quick fix would be to change the k3d clusters server URL from `https://0.0.0.0:63376` to  `https://127.0.0.1:63376` in the `.kube\config` file. Could you try that?

**Comment by Cyneath** [comment]
> A quick fix would be to change the k3d clusters server URL from `https://0.0.0.0:63376` to `https://127.0.0.1:63376` in the `.kube\config` file. Could you try that?

Yes, after I changed the URL the error disappeared. Everything else seems to work fine.

**Comment by deepu105** [comment]
Docker on windows is still weird :joy:

**Comment by deepu105** [comment]
I'll close the ticket as there isn't much I can do on Kdash for this, except may be document this. I'll see if I can do a PR on the kube lib to handle this though
