### ISSUE TITLE
Add filtering for resource views

### ISSUE THREAD

**Issue by samoylovfp** [kdash-rs/kdash#211]
**Is your feature request related to a problem? Please describe.**
I have a set of pods that are related to the service I maintain and I often need to read logs from these.

**Describe the solution you'd like**
I'd like to press a button and write a filter expression or a pod name glob and see statuses/logs of pods that match it.

**Describe alternatives you've considered**
without dash I use `kubectl get po | grep something`

**Additional context**
I would like to take a crack at the implementation if the idea is welcome

**Comment by deepu105** [comment]
Yes please. I would love to have this in KDash and will be happy to help if you can start an implementation
