### ISSUE TITLE
Instance type label in Nodes tab

### ISSUE THREAD

**Issue by shinusuresh** [kdash-rs/kdash#223]
It would be great to have the instance-type label in the Nodes tab. This will help when you navigate between multiple cluster environments where you have different instance types.

`node.kubernetes.io/instance-type: "m3.medium"` - https://kubernetes.io/docs/reference/labels-annotations-taints/#nodekubernetesioinstance-type

**Comment by deepu105** [comment]
How does kubectl show this today?

**Comment by shinusuresh** [comment]
Not by default. Only possible via custom columns

`-o custom-columns=type:"metadata.labels.beta\.kubernetes\.io/instance-type"`

**Comment by deepu105** [comment]
I'm bit hesitant to add features that are very unique in demand and not
supported by default in Kubectl. I believe this feature would be useful
only when you use a cloud provider. Let me think about it.

Thanks & Regards,
Deepu

**Comment by shinusuresh** [comment]
Understood. 
Would it make sense to have a toggle columns feature around?

**Comment by deepu105** [comment]
Could you explain? what do you mean by toggle column?

Thanks & Regards,
Deepu

**Comment by shinusuresh** [comment]
Something like this in a typical aws console

![image](https://user-images.githubusercontent.com/2842927/182696151-649b69e3-d1bf-4d7d-b893-d4516cdf6c6d.png)

**Comment by deepu105** [comment]
Thats gonna make the implementation and UI quite complex TBH so I don't
think that fits the goal of KDash which is to provide a fast and simple
alternative for kubectl with good UX

**Comment by shinusuresh** [comment]
Ok. No worries.
