### ISSUE TITLE
kdash crashes after install

### ISSUE THREAD

**Issue by jtharm** [kdash-rs/kdash#286]
**Describe the bug**
kdash crashes after install.

**To Reproduce**
Install via brew, then launch kdash as per instructions and it crashes, screenshot below.

**Screenshots**
<img width="1553" alt="image" src="https://user-images.githubusercontent.com/22123580/201125582-f2e69c53-4dc9-4519-b613-6a07205e0d3c.png">

**Desktop (please complete the following information):**
 - macOS 12.6
 - default Terminal in macOS
 - bash: 3.2.57(1)-release
- kubectl client v1.22.15 
- kubectl server v1.23.13+IKS
- kdash 0.3.5

**Additional context**

[crash.toml.zip](https://github.com/kdash-rs/kdash/files/9981955/crash.toml.zip)

**Comment by deepu105** [comment]
Do you have an active context in your kubeconfig?

**Comment by deepu105** [comment]
It seems like there is no valid kubeconfig found in yoyur system, you need to have a kubeconfig with atleast one active cluster. I'm going to fix the error message to fail gracefully https://github.com/kdash-rs/kdash/issues/280

**Comment by deepu105** [comment]
Thats weird, coz the error message attached says that it cannot find a kube config
