### ISSUE TITLE
"Error from network dispatch channel closed"

### ISSUE THREAD

**Issue by velvia** [kdash-rs/kdash#29]
**Describe the bug**

I see `Error from network dispatch channel closed` when I launch kdash, this is printed repeatedly on the screen.
Is this because of configuration? 
I'm running Kubernetes using Azure Kubernetes Service.

**To Reproduce**
Steps to reproduce the behavior or a screencast

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS and OS version: [e.g. macOS 10.1 / Fedora 34 / WIndows 10]
 - Terminal name and version [e.g. Tilix, Yakuake, Gnome Terminal, Konsole, iTerm, Windows CMD]
 - Shell name and version [e.g. bash, zsh, fish, powershell]
 - Kubectl Client Version [e.g. 1.19]
 - Kubectl Server Version [e.g. 1.19]
 - KDash version [e.g. 0.0.8]

**Additional context**

**Comment by deepu105** [comment]
Could you please fill in the desktop details and screenshots plz. Do you have kubectl installed and working?

**Comment by kelsin** [comment]
I'm seeing this as well. kubectl working. Happens on any of my contexts, not just aws or gcp but also local kind. I'm on a mac laptop (10.15.7). I installed via homebrew.

```shell
> kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:41:02Z", GoVersion:"go1.15", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.9-gke.1900", GitCommit:"008fd38bf3dc201bebdd4fe26edf9bf87478309a", GitTreeState:"clean", BuildDate:"2021-04-14T09:22:08Z", GoVersion:"go1.15.8b5", Compiler:"gc", Platform:"linux/amd64"}
```

I use alacritty as a terminal but the same behavior happens in mac's Terminal.app. It happens inside or outside of tmux.

![Screen Shot 2021-08-05 at 8 16 35 AM](https://user-images.githubusercontent.com/40592/128375513-42c38df3-0b61-463f-9878-3ee11e3c4cf4.png)

The terminal "graphics" look very screwed up and then we get that "Error from network dispatch channel closed" just repeats on the screen over and over. As a not helpful data point, k9s does boot up and show info in all of these test cases.

**Comment by deepu105** [comment]
Any pointers on how to reproduce this? I'm having a hard time reproducing it

**Comment by kelsin** [comment]
Honestly no idea. I was told about the project via coworkers. Ran the homebrew install and was met with the above. I've only tried on my mac (my main work computer) but other than that I wasn't able to get the program to run. Googled and found this issue.

**Comment by velvia** [comment]
The only hint I have is that I’m behind a VPN.

**Comment by deepu105** [comment]
VPN could be factor. If any of you are willing to run the debug build using
Cargo that would be great. But if you don't want to install Rust toolchain,
I understand. I'll try to do some research as well
