### ISSUE TITLE
Yaml view should hide `managedFields` by default

### ISSUE THREAD

**Issue by clux** [kdash-rs/kdash#294]
**Is your feature request related to a problem? Please describe.**
A lot of scrolling in kdash is dedicated to getting around the big `managedFields` object in `metadata` (something `kubectl` hides by default unless you specify `--show-managed-fields`). It would be nice if the output we showed was more useful that way. Given that this is TUI user app, it's probably OK to hide this controller specific (and very verbose) field.

**Describe the solution you'd like**
Mutate output from the apiservers list/watch calls before showing it to the user.
Use `.meta_mut()` go get and clear `.managed_fields` or use [`ResourceExt`](https://docs.rs/kube/latest/kube/trait.ResourceExt.html#tymethod.managed_fields_mut) directly to do it:

```rust
use kube::{Resource, ResourceExt};
fn hide_managed_fields<K: Resource>(obj: &mut K) {
    obj.managed_fields_mut().clear();
}
```

**Comment by clux** [comment]
hm, this is a little hairier than that looking at the codebase because you are working with proxy objects rather than `Resource` directly. I could have a stab at this, but it would probably include a bit of refactoring in `KubeResource` if that's OK.

**Comment by deepu105** [comment]
Hi Thanks for checking this . Feel free to refactor it as long as it doesn't become too hard to maintain or to refactor in rhe future. I just went with the simplest solution at the time so there is definitely room for improvements all around
