### ISSUE TITLE
Add search for custom Ressources

### ISSUE THREAD

**Issue by mjcc30** [kdash-rs/kdash#306]
**Is your feature request related to a problem? Please describe.**
There is a lot of ressources that doesn't exist in a default cluster but are very common like:
- gateways.networking.istio.io
- clusterissuers.cert-manager.io

**Describe the solution you'd like**
Add support for custom or specific ressource to "More <0>" tab and enter into a search mode ?

**Describe alternatives you've considered**
I don't know if existe alternatives for this but something like fzf research ?

**Comment by deepu105** [comment]
This would be nice but would need a very generic implementation to support
multiple types. I might not have time to look into into anytime soon. 8f
you have an idea, PR would be appreciated

**Comment by deepu105** [comment]
This is implemented in v0.4, can you check and give feedback?

**Comment by kolloch** [comment]
Heyo! I came here wanting to suggest this feature.

how can I trigger the search? I cannot figure that out.

**Comment by deepu105** [comment]
There is global filter that you trigger by hitting the `f` key

Thanks & Regards,
Deepu
