### ISSUE TITLE
Allow to filter namespaces

### ISSUE THREAD

**Issue by daxartio** [kdash-rs/kdash#310]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when i look for my namespaces from a lot of them (>100).

**Describe the solution you'd like**
I want to filter namespaces and show only my namespaces by a regex pattern. Also be good if i can search namespace by name

**Describe alternatives you've considered**

**Additional context**

**Comment by deepu105** [comment]
can be part of #211
