### ISSUE TITLE
Panic on large tick rate

### ISSUE THREAD

**Issue by aragilar** [kdash-rs/kdash#357]
**Describe the bug**
name = "kdash"
operating_system = "Debian n/a (trixie) [64-bit]"
crate_version = "0.4.0"
explanation = """
Panic occurred in file '/home/aragilar/.cargo/registry/src/github.com-1ecc6299db9ec823/kdash-0.4.0/src/main.rs' at line 65
"""
cause = "Tick rate must be below 1000"
method = "Panic"
backtrace = """

   0: 0x55725eaa90fe - kdash::main::h3e6ae10e51ac39ef
   1: 0x55725e8d43b3 - std::sys_common::backtrace::__rust_begin_short_backtrace::h9f740cf48ddacc56
   2: 0x55725eab771b - main
   3: 0x7f49db9886ca - __libc_start_call_main
                at ./csu/../sysdeps/nptl/libc_start_call_main.h:58
   4: 0x7f49db988785 - __libc_start_main_impl
                at ./csu/../csu/libc-start.c:360
   5: 0x55725e833e71 - _start
   6:        0x0 - <unresolved>"""

**To Reproduce**
`kdash -t 10000`

**Expected behavior**
Not panic.

**Comment by aragilar** [comment]
Related:
name = "kdash"
operating_system = "Debian n/a (trixie) [64-bit]"
crate_version = "0.4.0"
explanation = """
Panic occurred in file '/home/aragilar/.cargo/registry/src/github.com-1ecc6299db9ec823/kdash-0.4.0/src/main.rs' at line 68
"""
cause = "Poll rate must be multiple of tick-rate"
method = "Panic"
backtrace = """

   0: 0x56413721b0fe - kdash::main::h3e6ae10e51ac39ef
   1: 0x5641370463b3 - std::sys_common::backtrace::__rust_begin_short_backtrace::h9f740cf48ddacc56
   2: 0x56413722971b - main
   3: 0x7fbfb246d6ca - __libc_start_call_main
                at ./csu/../sysdeps/nptl/libc_start_call_main.h:58
   4: 0x7fbfb246d785 - __libc_start_main_impl
                at ./csu/../csu/libc-start.c:360
   5: 0x564136fa5e71 - _start
   6:        0x0 - <unresolved>"""

via `kdash -t 999` which shoudn't panic either.

**Comment by deepu105** [comment]
Those are intentional validation errors
