### ISSUE TITLE
Chocolatey Package for 0.4.3 is not available

### ISSUE THREAD

**Issue by madduci** [kdash-rs/kdash#386]
**Describe the bug**
In the documentation is stated that `kdash` 0.4.3 can be installed on Windows with `choco upgrade kdash --version=0.4.3`. On chocolatey the latest version available is the 0.4.2, so the instructions of the README file are not working.

**To Reproduce**
Steps to reproduce the behavior or a screencast
1. Open a CMD Terminal with administrative rights on Windows
2. type `choco upgrade kdash --version=0.4.3`
3. See error

**Expected behavior**
`kdash` 0.4.3 is installed correctly

**Screenshots**
![image](https://github.com/kdash-rs/kdash/assets/371042/59bad3e9-d851-4279-bb53-b4e7a38d0acd)

**Desktop (please complete the following information):**
 - OS and OS version: Windows 10 22H2
 - Terminal name and version: Windows CMD
 - Shell name and version: CMD
 - Kubectl Client Version: 1.26.6
 - Kubectl Server Version: 1.26.6
 - KDash version: 0.4.3

**Additional context**
None

**Comment by deepu105** [comment]
chocolatey sucks takes forever to verify and publish packages (Its not in my control). Please use scoop or install the executable directly. The package eventually will be avialbel but I have no idea how long it takes.
