### ISSUE TITLE
Add support for Storage classes

### ISSUE THREAD

**Issue by deepu105** [kdash-rs/kdash#50]
Add support for Storage classes

**Comment by shinusuresh** [comment]
Hey @deepu105, I would like to take a look at this issue. Heads up, pretty new to rust.

**Comment by shinusuresh** [comment]
Hey, How is this looking like?

![image](https://user-images.githubusercontent.com/2842927/178550696-870ff21b-9b69-4277-8cca-7f8b1f66e42d.png)

Any additional fields to be added?

**Comment by deepu105** [comment]
Looking good. Idea is to show same fields as kubectl

**Comment by shinusuresh** [comment]
Ha Nice. I will amend the PR to add VOLUMEBINDINGMODE and ALLOWVOLUMEEXPANSION

**Comment by deepu105** [comment]
Awesome thanks. Will do as soon as I'm back

**Comment by deepu105** [comment]
Feel free to do more PRs in the meantime if you are interested 😜
