### ISSUE TITLE
Add support for Service accounts

### ISSUE THREAD

**Issue by deepu105** [kdash-rs/kdash#57]
Add support for Service accounts

**Comment by kunalsumblyavenue** [comment]
I am interested to contribute, how do I go about it ?  Is the intention to get all the service accounts under a specific namespace?  I am new to rust , though.

**Comment by deepu105** [comment]
I would recommend starting with the official Rust book. Its a great source to get started and understand basics of the language. For this feature, the idea is to show the output similar to `kubectl get serviceaccounts -A`

**Comment by deepu105** [comment]
done
