### ISSUE TITLE
Crash on exit

### ISSUE THREAD

**Issue by wintermi** [kdash-rs/kdash#79]
**Describe the bug**
Application crashes when exiting via the ESC key.

**To Reproduce**
Steps to reproduce the behavior or a screencast
1. Open application
2. Hit the ESC key
3. Crash

**Expected behavior**
Gracefully exit the application

**Desktop (please complete the following information):**
 - OS and OS version: RHEL 8.4
 - Terminal name and version: kitty
 - Shell name and version: bash 4.4.20
 - Kubectl Client Version: 1.20.5
 - Kubectl Server Version: 1.20.5
 - KDash version: 0.2.0

**Comment by deepu105** [comment]
Is there an error message when this happens?

**Comment by wintermi** [comment]
The following is display on exit when it crashes:
<img width="1339" alt="Screen Shot 2021-07-16 at 7 44 02 pm" src="https://user-images.githubusercontent.com/33818/125933286-6ac85a8c-3e08-426a-a060-73d743fd9558.png">

Error File Contains:
```
name = 'kdash'
operating_system = 'unix:Unknown'
crate_version = '0.2.0'
explanation = '''
Panic occurred in file '/home/matt/.cargo/registry/src/github.com-1ecc6299db9ec823/kdash-0.2.0/src/app/mod.rs' at line 463
'''
cause = 'index out of bounds: the len is 1 but the index is 18446744073709551615'
method = 'Panic'
backtrace = '''

   0: 0x561040c7bb75 - kdash::main::{{closure}}::h91354381db050615
   1: 0x561040c74460 - kdash::main::h6ab710448b55fcde
   2: 0x561040b36933 - std::sys_common::backtrace::__rust_begin_short_backtrace::ha6f877531958c7db
   3: 0x561040c7ffc4 - main
   4: 0x7fa14577c493 - __libc_start_main
   5: 0x561040aac12e - _start
   6:        0x0 - <unresolved>'''
```

**Comment by deepu105** [comment]
Thank you let me check. When did you press ESC, was it on the overview page
or somewhere else, also what were you trying to do?

Thanks & Regards,
Deepu

**Comment by wintermi** [comment]
If you open the application and do nothing and hit the ESC key it will error out with the above message.  If I press `q` then the application exits gracefully.  This is on the overview page.  As for what I am doing, one purpose would be to watch a large deployment.

**Comment by deepu105** [comment]
Thanks for the info. I'll fix it in next release
