### ISSUE TITLE
Page Up / Down Support

### ISSUE THREAD

**Issue by wintermi** [kdash-rs/kdash#80]
**Is your feature request related to a problem? Please describe.**
I would like to be able to scroll down the list of pods quickly, adding support for Page Up / Down via the same keys would aid with this. 

**Describe the solution you'd like**
Allow for the Page Up and Page Down key to be used to perform page scrolls within any of the screens.  

**Describe alternatives you've considered**
Scrolling down using the cursor keys is slow, an alternative would be to make the overal scroll performance faster

**Comment by deepu105** [comment]
Thanks for the feature request. Sounds like a good UX feature. I'll
implement this for next release
