### ISSUE TITLE
kdash Crash Report

### ISSUE THREAD

**Issue by ifraixedes** [kdash-rs/kdash#82]
**Describe the bug**

Report a crash report as it's asked when it happens.

**To Reproduce**
Steps to reproduce the behavior or a screencast

Perhaps I did something but I cannot reproduce the crash again doing what I remember that I did when it crashed.

I was in the utilization tab and I have several context configured.

**Desktop (please complete the following information):**
 - OS and OS version `Ubuntu 20.04 docker container` with several tools installed
 - Terminal name and version `tmux 3.0a`
 - Shell name and version `zsh 5.8 (x86_64-ubuntu-linux-gnu)`
 - Kubectl Client Version `1.17.14`
 - Kubectl Server Version `1.18.17-gke.1901`
 - KDash version `0.1.2`

**Additional context**

Crash report content:

```
name = 'kdash'
operating_system = 'unix:Ubuntu'
crate_version = '0.1.2'
explanation = '''
Panic occurred in file '/home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tui-0.15.0/src/widgets/table.rs' at line 359
'''
cause = 'index out of bounds: the len is 72 but the index is 127'
method = 'Panic'
backtrace = '''

   0: 0x7f1102848c82 - <unresolved>
   1: 0x7f1102aeccae - <unresolved>
   2: 0x7f11029b9e03 - <unresolved>
   3: 0x7f1102a9e1d2 - <unresolved>
   4: 0x7f110299b548 - <unresolved>
   5: 0x7f110293d092 - <unresolved>
   6: 0x7f11029ae629 - <unresolved>
   7: 0x7f1102a90a14 - <unresolved>
   8: 0x7f1102a1f9ea - <unresolved>
   9: 0x7f11028fe8c3 - <unresolved>
  10: 0x7f1102a00f0d - <unresolved>
  11: 0x7f1102f3bfa9 - <unresolved>
  12: 0x7f1102a200e2 - <unresolved>'''
```

**Comment by deepu105** [comment]
I think its the same issue as #77

**Comment by deepu105** [comment]
clsoing in favor of #77

**Comment by deepu105** [comment]
Thanks for the report
