### ISSUE TITLE
Log streaming is blocking network thread even after break

### ISSUE THREAD

**Issue by deepu105** [kdash-rs/kdash#9]
When streaming container logs, the network thread gets blocked for any subsequent calls (when going back and selecting a new container). Seems like when the `try_next` on the logs stream waits for a server response (incase of a container that doesn't produce next line of log yet) the thread gets blocked

log_streaming_method: https://github.com/kdash-rs/kdash/blob/main/src/network/kube_api.rs#L394

**Comment by deepu105** [comment]
Hey @clux do you think this is an issue or just me doing something wrong

**Comment by clux** [comment]
Yeah, the `try_next` will await a next log line, so it's expected that you keep streaming until you decide not to stream anymore.

It shouldn't block any network threads, kube doesn't have anything like that. I'm guessing (without digging too deeply) that you need to spawn more tasks in your program - maybe dedicate a task to buffering it (depending on how you are presenting it) - or maybe you're locking your app for longer than you expect.

**Comment by deepu105** [comment]
Is there  way to stop streaming? I tried droping the logs instance but it still seems to lock

**Comment by clux** [comment]
I think if you drop the result of `kube::Api`'s log stream, it **should** end, unless you are still awaiting.

The general advice here should be to either stop awaiting, by putting a [timeout](https://docs.rs/tokio-stream/0.1.5/tokio_stream/trait.StreamExt.html#method.timeout) on the stream, or buffer the data in the background instead.

**Comment by deepu105** [comment]
I created a new thread for streams, the network thread seems to be fine now, but the stream thread gets blocked now. I'll try the timeout. thanks for the hint. This is where I wish for cancellable streams :cry:

**Comment by clux** [comment]
> This is where I wish for cancellable streams

Agreed. I think you also can Box the stream and wrap it in an [Abortable](https://docs.rs/futures/0.3.14/futures/future/struct.Abortable.html), but haven't played around much with this myself.

**Comment by deepu105** [comment]
Switched from `futures::TryStreamExt` to `tokio_stream::StreamExt` and used the timeout method. It works well now. Thanks man. You are awesome. I wish someone like contributed to this project :joy:

**Comment by deepu105** [comment]
fixed via https://github.com/kdash-rs/kdash/commit/d25861dc8667380c5b8490f5af0b0487e5410492

**Comment by deepu105** [comment]
actually fixed by https://github.com/kdash-rs/kdash/commit/55ba5fb004b2a897ce3938d5044f2d2aafb7cac0
