### ISSUE TITLE
Missing docker latest image

### ISSUE THREAD

**Issue by agravelot** [kdash-rs/kdash#91]
**Describe the bug**
Running given docker command will fail to execute because no image is available for latest tag.

**To Reproduce**
```bash
$ docker run --rm -it -v ~/.kube/config:/root/.kube/config deepu105/kdash

docker: Error response from daemon: manifest for deepu105/kdash:latest not found: manifest unknown: manifest unknown.
```

**Expected behavior**
Being able to get the latest version without tag.

**Comment by deepu105** [comment]
Thanks for the report. I have fixed this, can you try again?

**Comment by agravelot** [comment]
Fixed, thanks 👍🏻
